name: Bug report
description: Create a bug report
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        # A bug means something doesn't work as expected
        Remember to include as much detail as possible.

  - type: input
    id: commit
    attributes:
      label: zig-cassandra commit
      description: "The git commit of zig-cassandra"
    validations:
      required: true

  - type: input
    id: zig_version
    attributes:
      label: Zig version
      description: "The output of `zig version`"
      placeholder: "0.13.0-dev.267+793f820b3"
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: How can someone reproduce the problem you encountered ? Include a self-contained reproducer if possible
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true
